#!/bin/sh

ARGS=1
BF_OPTIONS=
while [ $ARGS != 0 ]
do
	case "$1" in
		nodoc)
			BF_OPTIONS="-DBUILDDOCS=no $BF_OPTIONS"
			shift
			;;

		noex)
			BF_OPTIONS="-DBUILDEXAMPLES=no $BF_OPTIONS"
			shift
			;;

		nolib)
			BF_OPTIONS="-DBUILDLIBRARY=no $BF_OPTIONS"
			shift
			;;

		noopt)
			export CXXFLAGS="-g -O0"
			shift
			;;

		pedantic)
			export CXXFLAGS="-g -O2 -ansi -pedantic -Wall -W -Wold-style-cast -Wfloat-equal -Wwrite-strings -Woverloaded-virtual -Wno-long-long"
			shift
			;;

		vstudio)
			cmd /c rebake.bat $BF_OPTIONS
			exit 0
			;;

		*)
			ARGS=0
			;;
	esac
done

rm -f config.cache
set -x

bakefilize &&
	bakefile_gen $BF_OPTIONS &&
	mv autoconf_inc.m4 config ;
	unix2dos *.ds? > /dev/null 2>&1 ;
	bakefile -f gnu -o Makefile.simple -DBUILDLIBRARY=no mysql++.bkl &&
	aclocal -I config -I /usr/local/share/aclocal &&
	autoheader &&
	autoconf &&
	./reconf --enable-maintainer-mode $* &&
	make lib/custom.h lib/querydef.h

