#!/bin/sh

ARGS=1
BF_OPTIONS=
while [ $ARGS != 0 ]
do
	case "$1" in
		nodoc)
			BF_OPTIONS="-DBUILDDOCS=no $BF_OPTIONS"
			shift
			;;

		noex)
			BF_OPTIONS="-DBUILDEXAMPLES=no $BF_OPTIONS"
			shift
			;;

		nolib)
			BF_OPTIONS="-DBUILDLIBRARY=no $BF_OPTIONS"
			shift
			;;

		noopt)
			export CXXFLAGS="-g -O0"
			shift
			;;

		pedantic)
			export CXXFLAGS="-g -O2 -ansi -pedantic -Wall -W -Wold-style-cast -Wfloat-equal -Wwrite-strings -Wno-overloaded-virtual -Wno-long-long -Wno-variadic-macros"
			shift
			;;

		vstudio)
			cmd /c rebake.bat $BF_OPTIONS
			exit 0
			;;

		*)
			ARGS=0
			;;
	esac
done

rm -f config.cache

# Do Bakefile stuff first
set -x &&
	bakefilize &&
	bakefile_gen $BF_OPTIONS &&
	bakefile -f gnu -o Makefile.simple -DBUILDLIBRARY=no mysql++.bkl &&
	set +x &&
	success=shonuff

# If that succeeded, move on to autotools stuff, etc.
if [ -n "$success" ]
then
	mv autoconf_inc.m4 config > /dev/null 2>&1	# don't care if it fails

	success=
	aclocal -I config -I /usr/local/share/aclocal &&
		autoheader &&
		autoconf &&
		./configure --cache-file=config.cache --enable-maintainer-mode $* &&
		make lib/custom.h lib/querydef.h &&
		set +x &&
		success=awyeah
fi

# Detect failure in any part of above
if [ -z "$success" ]
then
    echo BOOTSTRAP FAILED!
    echo
    exit 1
fi

