#!/bin/sh
## Major configurables
RPMDIR=/usr/src/redhat
RPMBINDIR=$RPMDIR/RPMS/i386
RPMSRCDIR=$RPMDIR/SRPMS
DESTHOST=tangent@tangent.dyndns.org
DESTDIR=projects/tangentsoft.net/mysql++/releases
DEST=$DESTHOST:$DESTDIR

## Find out what OS we're running on, so we can name the RPMs with a tag
## saying where they were built.
ISSUE=`head -1 /etc/issue`
echo $ISSUE | grep -q 'Red Hat'
RH=$?
echo $ISSUE | grep -q 'Fedora Core'
FC=$?
if [ $RH == 0 ]
then
	OS=rh`echo $ISSUE | awk '{ print $5 }'`
elif [ $FC == 0 ]
then
	OS=fc`echo $ISSUE | awk '{ print $4 }'`
else
	OS=unknown
fi

## Find out MySQL++ version number, including the package subrev.
VERSION=`grep ' VERSION' config.h | awk '{ print $3 }' | tr -d \"`
if [ -n "$1" ]
then
	VERSION=$VERSION-$1
else
	VERSION=$VERSION-1
fi
echo Uploading MySQL++ $VERSION...

## Decide whether the sources should be uploaded...
SRCRPM=$RPMSRCDIR/mysql++-$VERSION.src.rpm 
TARBALL=mysql++-$VERSION.tar.gz 
SRCVERFILE=/pub/mysql++-src-ver
if [ -e $SRCVERFILE ]
then
	SRCUPVER=`cat $SRCVERFILE`
else
	SRCUPVER='booga'
fi

if [ "$SRCUPVER" == "$VERSION" ]
then
	echo "   sources already copied..."
	SOURCES=""
else
	SOURCES="$TARBALL $SRCRPM "
	echo -n $VERSION > $SRCVERFILE
fi

## Make a renamed copy of the binary RPMs, to give them the OS tag.
TMPDIR=`mktemp -d /tmp/rpmup.XXXXXX`
BINRPM=$TMPDIR/mysql++-$VERSION.$OS.i386.rpm
DEVRPM=$TMPDIR/mysql++-devel-$VERSION.$OS.i386.rpm
cp $RPMBINDIR/mysql++-$VERSION.i386.rpm $BINRPM
cp $RPMBINDIR/mysql++-devel-$VERSION.i386.rpm $DEVRPM

scp $SOURCES$BINRPM $DEVRPM $DEST

rm -r $TMPDIR
