#!/bin/sh

echo 'Running tests:'
echo -n "   "
TMP=`mktemp bmXXXXXX`
# Yes, the repeated use of resetdb is intentional!  We're running it
# after the examples that change the database in a way that will cause
# subsequent examples to fail because data they need isn't present.
for t in test_* \
	resetdb simple[0-9] store_if for_each multiquery tquery1 \
	resetdb tquery2 dbinfo fieldinf \
	resetdb usequery custom[0-9]
do
	if [ -x $t ]
	then
		if [ "$t" = "resetdb" ]
		then
			echo
			echo -n "   "
		fi
	
		echo -n "$t "
		echo "---------------- BEGIN $t OUTPUT ----------------" >> $TMP
		if ! ./exrun $t -D $* >> $TMP
		then
			echo
			echo 'TESTING ABORTED.'
			rm -f $TMP
			exit $?
		fi
		echo "================ END $t OUTPUT ================" >> $TMP
		echo >> $TMP
	fi
done
echo

BFILE=bmark.txt
if [ -f $BFILE ]
then
	if diff -u -w $BFILE $TMP
	then
		echo
		echo 'No changes in test results.'
	fi
	rm -f $TMP
else
	mv $TMP $BFILE
	chmod -w $BFILE
	echo
	echo 'Benchmark file regenerated.'
fi
