#!/bin/sh

# Disable UTF-8 translation stuff
export LANG=C

echo -n "Running tests: "
TMP=`mktemp bmXXXXXX`
for t in resetdb simple1 simple2 simple3 multiquery tquery usequery \
	custom1 custom2 custom3 custom4 custom5 custom6 store_if for_each
do
	if [ -x $t ]
	then
		echo -n "$t "
		echo "---------------- BEGIN $t OUTPUT ----------------" >> $TMP
		if ! ./exrun $t $* >> $TMP
		then
			echo
			echo 'TESTING ABORTED.'
			rm -f $TMP
			exit $?
		fi
		echo "================ END $t OUTPUT ================" >> $TMP
	else
		echo "Failed to find test program $t. Is it built?"
		rm -f $TMP
		exit 101
	fi
done
echo

BFILE=bmark.txt
if [ -f $BFILE ]
then
	if diff -u -w $BFILE $TMP
	then
		echo 'No changes in test results.'
	fi
	rm -f $TMP
else
	mv $TMP $BFILE
	chmod -w $BFILE
	echo 'Benchmark file regenerated.'
fi
