#!/bin/sh
if [ ! -e ../lib/libmysqlpp.so.2 ]
then
	( cd ../lib ; ln -sf libmysqlpp.so libmysqlpp.so.2 )
fi

PROG=$1
shift

if [ -e /usr/bin/ldd ]
then
	LD_LIBRARY_PATH=../lib ./$PROG $*
elif [ -e /usr/bin/otool ]
then
	DYLD_LIBRARY_PATH=../lib ./$PROG $*
else
	echo ERROR: I don\'t grok this system\'s dynamic linkage system.
fi
